# Generated by Django 4.1.1 on 2022-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('lecture_hours', models.IntegerField(null=True)),
                ('tutorial_hours', models.IntegerField(null=True)),
                ('practical_hours', models.IntegerField(null=True)),
                ('j_proj_hours', models.IntegerField(null=True)),
                ('credits', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('school', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('course_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('no_of_wishlist_recieved', models.IntegerField(null=True)),
            ],
        ),
    ]
