# Generated by Django 4.1.1 on 2022-09-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('p1', models.CharField(max_length=200)),
                ('p2', models.CharField(max_length=200)),
                ('p3', models.CharField(max_length=200)),
                ('p4', models.CharField(max_length=200)),
                ('p5', models.CharField(max_length=200)),
                ('a1', models.CharField(max_length=200, null=True)),
                ('a2', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
