# Generated by Django 4.1.1 on 2022-09-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('course_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('no_of_batches', models.IntegerField()),
                ('after_prof', models.IntegerField(null=True)),
            ],
        ),
    ]
